language: php

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        -
            php: 7.0
            script:
                - make phpunit
                - make php-cs-fixer-dry-run
        -
            php: 7.1
            script:
                - make phpunit
        -
            php: 7.2
            script:
                - make phpunit
        -
            php: 7.3
            script:
                - make phpunit
        -
            php: 7.4snapshot
            script:
                - make phpunit
